# Generated by Django 6.0.4 on 2026-04-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DONOR', 'Donor'), ('VOLUNTEER', 'Volunteer'), ('BENEFICIARY', 'Beneficiary'), ('NGO_EMPLOYEE', 'NGO Employee')], default='DONOR', max_length=20),
        ),
    ]
