# Generated by Django 6.0.4 on 2026-04-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_auto_fix_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor_birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_blood_type',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_last_donation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
