# Generated by Django 6.0 on 2026-05-01 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_aidrequest_approved_by_ngo_and_more'),
        ('donations', '0007_donation_donor_birth_date_donation_donor_blood_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='aid_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='cases.aidrequest'),
        ),
        migrations.AddField(
            model_name='donation',
            name='assigned_ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_case_donations', to=settings.AUTH_USER_MODEL),
        ),
    ]
