# Generated by Django 6.0 on 2026-05-01 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_existing_approved_cases(apps, schema_editor):
    AidRequest = apps.get_model('cases', 'AidRequest')
    AidRequest.objects.filter(status='APPROVED').update(ngo_status='APPROVED')


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aidrequest',
            name='approved_by_ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_aid_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aidrequest',
            name='ngo_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aidrequest',
            name='ngo_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aidrequest',
            name='ngo_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.RunPython(
            preserve_existing_approved_cases,
            migrations.RunPython.noop,
        ),
    ]
